# (id_dataset o None, nombre, patron, lumbar, medida|None, [alias], svg|None)
# patron: empuje_h empuje_v tiron_h tiron_v sentadilla bisagra unilateral cuadriceps femoral gluteo aductores abductores
#         pecho_ais hombro_lat hombro_post hombro_front trapecio biceps triceps gemelos antebrazo
#         core_flex core_anti core_rot carga potencia pliometria cardio
L = [
# ---------- PECHO / EMPUJE HORIZONTAL
("Barbell_Bench_Press_-_Medium_Grip","Press banca plano con barra","empuje_h","baja",None,["press banca","press banca plano","press banca con barra","press de banca","press plano","bench press"],"bench-press.svg"),
("Barbell_Incline_Bench_Press_-_Medium_Grip","Press inclinado con barra","empuje_h","baja",None,["press banca inclinado","press inclinado","press inclinado barra"],None),
("Decline_Barbell_Bench_Press","Press declinado con barra","empuje_h","baja",None,["press banca declinado","press declinado"],None),
("Wide-Grip_Barbell_Bench_Press","Press banca agarre abierto","empuje_h","baja",None,[],None),
("Close-Grip_Barbell_Bench_Press","Press banca agarre cerrado","empuje_h","baja",None,["press cerrado","press banca cerrado"],"narrow-grip-bench-press.svg"),
("Dumbbell_Bench_Press","Press banca con mancuernas","empuje_h","baja",None,["press plano con mancuernas","press con mancuernas","press de pecho con mancuernas"],None),
("Incline_Dumbbell_Press","Press inclinado con mancuernas","empuje_h","baja",None,["press banca inclinado con mancuernas","press inclinado mancuernas"],None),
("Decline_Dumbbell_Bench_Press","Press declinado con mancuernas","empuje_h","baja",None,[],None),
("Hammer_Grip_Incline_DB_Bench_Press","Press inclinado con mancuernas agarre neutro","empuje_h","baja",None,[],None),
("Dumbbell_Bench_Press_with_Neutral_Grip","Press con mancuernas agarre neutro","empuje_h","baja",None,[],None),
("One_Arm_Dumbbell_Bench_Press","Press banca a una mano","empuje_h","baja",None,[],"one-arm-bench-press.svg"),
("Machine_Bench_Press","Press de pecho en máquina","empuje_h","baja",None,["press en maquina","press pecho maquina","press de pecho maquina","chest press"],None),
("Leverage_Chest_Press","Press de pecho en máquina convergente","empuje_h","baja",None,["press hammer","press convergente"],None),
("Leverage_Incline_Chest_Press","Press inclinado en máquina","empuje_h","baja",None,["press inclinado maquina"],None),
("Leverage_Decline_Chest_Press","Press declinado en máquina","empuje_h","baja",None,[],None),
("Smith_Machine_Bench_Press","Press banca en Smith","empuje_h","baja",None,["press banca en multipower","press smith"],None),
("Smith_Machine_Incline_Bench_Press","Press inclinado en Smith","empuje_h","baja",None,["press inclinado multipower"],None),
("Cable_Chest_Press","Press de pecho en polea","empuje_h","baja",None,[],None),
("Pushups","Flexiones de brazos","empuje_h","baja","reps",["flexiones","lagartijas","push ups"],"push-ups.svg"),
("Push-Ups_With_Feet_Elevated","Flexiones con pies elevados","empuje_h","baja","reps",["flexiones declinadas"],None),
("Incline_Push-Up","Flexiones inclinadas (manos elevadas)","empuje_h","baja","reps",[],"push-up.svg"),
("Single-Arm_Push-Up","Flexiones a una mano","empuje_h","baja","reps",[],"one-armed-biased-push-up.svg"),
("Dips_-_Chest_Version","Fondos en paralelas para pecho","empuje_h","baja","reps",["fondos pecho"],None),
("Dumbbell_Flyes","Aperturas con mancuernas","pecho_ais","baja",None,["aperturas","aperturas planas","vuelos con mancuernas"],"dumbbell-flys.svg"),
("Incline_Dumbbell_Flyes","Aperturas inclinadas con mancuernas","pecho_ais","baja",None,["aperturas inclinadas"],"dumbbell-decline-flys.svg"),
("Decline_Dumbbell_Flyes","Aperturas declinadas con mancuernas","pecho_ais","baja",None,["aperturas declinadas"],None),
("Butterfly","Peck deck (aperturas en máquina)","pecho_ais","baja",None,["peck deck","pec deck","contractor","mariposa","aperturas en maquina"],None),
("Cable_Crossover","Cruce de poleas","pecho_ais","baja",None,["crossover","cruce de poleas alto","cruces en polea"],None),
("Low_Cable_Crossover","Cruce de poleas desde abajo","pecho_ais","baja",None,["cruce de poleas bajo"],None),
("Flat_Bench_Cable_Flyes","Aperturas en polea en banco plano","pecho_ais","baja",None,[],None),
("Incline_Cable_Flye","Aperturas en polea en banco inclinado","pecho_ais","baja",None,[],None),
("Bent-Arm_Dumbbell_Pullover","Pullover con mancuerna","pecho_ais","baja",None,["pullover","pull over"],"bent-arm-pullover.svg"),
# ---------- TIRÓN VERTICAL
("Pullups","Dominadas","tiron_v","baja","reps",["dominadas pronas","pull ups"],"gironda-sternum-chins.svg"),
("Chin-Up","Dominadas supinas","tiron_v","baja","reps",["chin up","dominadas agarre supino"],None),
("Band_Assisted_Pull-Up","Dominadas asistidas con banda","tiron_v","baja","reps",[],None),
(None,"Dominadas asistidas en máquina","tiron_v","baja",None,["dominada asistida","dominadas asistidas","maquina de dominadas asistidas","dominadas en maquina"],None),
("Weighted_Pull_Ups","Dominadas con lastre","tiron_v","baja",None,[],None),
("Wide-Grip_Lat_Pulldown","Jalón al pecho agarre abierto","tiron_v","baja",None,["jalon al pecho","jalon","polea al pecho","lat pulldown","jalon dorsal"],None),
("Close-Grip_Front_Lat_Pulldown","Jalón al pecho agarre cerrado","tiron_v","baja",None,[],None),
("V-Bar_Pulldown","Jalón con triángulo","tiron_v","baja",None,["jalon agarre neutro","jalon con v"],None),
("Underhand_Cable_Pulldowns","Jalón supino","tiron_v","baja",None,["jalon al pecho supino"],None),
("One_Arm_Lat_Pulldown","Jalón a una mano","tiron_v","baja",None,[],None),
("Straight-Arm_Pulldown","Pullover en polea (brazos rectos)","tiron_v","baja",None,["pullover en polea","jalon brazos rectos"],None),
("Rope_Straight-Arm_Pulldown","Pullover en polea con soga","tiron_v","baja",None,[],None),
("Kneeling_High_Pulley_Row","Remo en polea alta arrodillado","tiron_v","baja",None,[],None),
# ---------- TIRÓN HORIZONTAL
("Bent_Over_Barbell_Row","Remo con barra","tiron_h","alta",None,["remo inclinado con barra","remo con barra pronado","remo barra"],None),
("Reverse_Grip_Bent-Over_Rows","Remo con barra agarre supino","tiron_h","alta",None,["remo supino con barra"],None),
("One-Arm_Dumbbell_Row","Remo con mancuerna a una mano","tiron_h","baja",None,["remo serrucho","remo a una mano","remo con mancuerna"],None),
("Bent_Over_Two-Dumbbell_Row","Remo inclinado con dos mancuernas","tiron_h","media",None,["remo con mancuernas"],None),
("Dumbbell_Incline_Row","Remo con pecho apoyado en banco inclinado","tiron_h","baja",None,["remo pecho apoyado","remo en banco inclinado con mancuernas"],None),
("Seated_Cable_Rows","Remo sentado en polea","tiron_h","baja",None,["remo bajo","remo en polea baja","remo gironda","remo sentado","remo en polea"],None),
("Seated_One-arm_Cable_Pulley_Rows","Remo en polea a una mano","tiron_h","baja",None,[],None),
("Leverage_Iso_Row","Remo en máquina","tiron_h","baja",None,["remo maquina","remo convergente","remo en maquina sentado"],None),
("Leverage_High_Row","Remo alto en máquina","tiron_h","baja",None,[],None),
("Lying_T-Bar_Row","Remo T con pecho apoyado","tiron_h","baja",None,["remo t apoyado"],None),
("T-Bar_Row_with_Handle","Remo T con barra","tiron_h","alta",None,["remo t","remo con barra t","remo en t"],"t-bar-row.svg"),
("Smith_Machine_Bent_Over_Row","Remo en Smith","tiron_h","alta",None,[],None),
("Inverted_Row","Remo invertido","tiron_h","baja","reps",["remo australiano"],None),
("Incline_Bench_Pull","Remo con barra en banco inclinado","tiron_h","baja",None,[],None),
# ---------- HOMBRO: EMPUJE VERTICAL
("Standing_Military_Press","Press militar con barra de pie","empuje_v","media",None,["press militar","press militar de pie","press de hombros con barra","overhead press"],"one-arm-shoulder-press.svg"),
("Seated_Barbell_Military_Press","Press militar sentado con barra","empuje_v","baja",None,["press militar sentado"],None),
("Dumbbell_Shoulder_Press","Press de hombros con mancuernas","empuje_v","baja",None,["press de hombro con mancuernas","press hombro mancuernas","press de hombros"],None),
("Seated_Dumbbell_Press","Press de hombros sentado con mancuernas","empuje_v","baja",None,["press sentado con mancuernas"],None),
("Standing_Dumbbell_Press","Press de hombros de pie con mancuernas","empuje_v","media",None,[],None),
("Arnold_Dumbbell_Press","Press Arnold","empuje_v","baja",None,["press arnold"],"arnold-press.svg"),
("Machine_Shoulder_Military_Press","Press de hombros en máquina","empuje_v","baja",None,["press militar en maquina","press hombro maquina"],None),
("Leverage_Shoulder_Press","Press de hombros en máquina convergente","empuje_v","baja",None,[],None),
("Smith_Machine_Overhead_Shoulder_Press","Press militar en Smith","empuje_v","baja",None,["press militar multipower"],None),
("Seated_Cable_Shoulder_Press","Press de hombros en polea","empuje_v","baja",None,[],None),
("Landmine_Linear_Jammer","Press landmine","empuje_v","media",None,["landmine press"],None),
("Handstand_Push-Ups","Flexiones en vertical (handstand)","empuje_v","baja","reps",[],None),
# ---------- HOMBRO: LATERAL / FRONTAL / POSTERIOR
("Side_Lateral_Raise","Elevaciones laterales con mancuernas","hombro_lat","baja",None,["elevaciones laterales","vuelos laterales","elevaciones laterales con mancuerna","laterales"],"dumbbell-lateral-raises.svg"),
("Seated_Side_Lateral_Raise","Elevaciones laterales sentado","hombro_lat","baja",None,[],None),
("Cable_Seated_Lateral_Raise","Elevaciones laterales en polea","hombro_lat","baja",None,["vuelos laterales en polea","laterales en polea"],None),
("One-Arm_Side_Laterals","Elevación lateral a una mano","hombro_lat","baja",None,[],None),
(None,"Elevaciones laterales en máquina","hombro_lat","baja",None,["laterales en maquina"],None),
("Upright_Barbell_Row","Remo al mentón con barra","hombro_lat","baja",None,["remo al menton","remo al cuello","remo parado"],"barbell-upright-rows.svg"),
("Standing_Dumbbell_Upright_Row","Remo al mentón con mancuernas","hombro_lat","baja",None,[],None),
("Dumbbell_One-Arm_Upright_Row","Remo al mentón a una mano","hombro_lat","baja",None,["remo al menton a una mano"],"one-arm-upright-row.svg"),
("Upright_Cable_Row","Remo al mentón en polea","hombro_lat","baja",None,[],None),
("Front_Dumbbell_Raise","Elevaciones frontales con mancuernas","hombro_front","baja",None,["elevaciones frontales","vuelos frontales"],"dumbbell-front-raises.svg"),
("Front_Cable_Raise","Elevaciones frontales en polea","hombro_front","baja",None,[],None),
("Front_Plate_Raise","Elevación frontal con disco","hombro_front","baja",None,["elevaciones frontales con disco"],None),
("Straight_Raises_on_Incline_Bench","Elevaciones frontales con barra","hombro_front","baja",None,["elevaciones frontales con barra"],"barbell-front-raises.svg"),
("Reverse_Flyes","Pájaros con mancuernas","hombro_post","baja",None,["pajaros","vuelos posteriores","aperturas inversas"],None),
("Lying_Rear_Delt_Raise","Pájaros acostado en banco","hombro_post","baja",None,[],"lying-rear-lateral-raise.svg"),
("Dumbbell_Lying_One-Arm_Rear_Lateral_Raise","Pájaros a una mano","hombro_post","baja",None,["pajaros a una mano"],"lying-one-arm-rear-lateral-raise.svg"),
("Seated_Bent-Over_Rear_Delt_Raise","Pájaros sentado","hombro_post","baja",None,[],None),
("Reverse_Machine_Flyes","Aperturas inversas en máquina","hombro_post","baja",None,["peck deck invertido","deltoides posterior en maquina","posterior en maquina"],None),
("Cable_Rear_Delt_Fly","Pájaros en polea","hombro_post","baja",None,["posterior en polea"],None),
("Face_Pull","Face pull","hombro_post","baja",None,["tiron a la cara","face pull con soga"],None),
("Cable_Rope_Rear-Delt_Rows","Remo posterior en polea con soga","hombro_post","baja",None,["remo posterior"],"rear-deltoid-row.svg"),
("Band_Pull_Apart","Separación de banda","hombro_post","baja","reps",["band pull apart"],None),
# ---------- TRAPECIO
("Barbell_Shrug","Encogimientos con barra","trapecio","baja",None,["encogimientos","encogimientos de hombros","shrugs"],"barbell-shrugs.svg"),
("Dumbbell_Shrug","Encogimientos con mancuernas","trapecio","baja",None,[],None),
("Cable_Shrugs","Encogimientos en polea","trapecio","baja",None,[],None),
("Leverage_Shrug","Encogimientos en máquina","trapecio","baja",None,[],None),
# ---------- BÍCEPS
("Barbell_Curl","Curl de bíceps con barra","biceps","baja",None,["curl con barra","curl biceps barra","curl barra recta"],"standing-biceps-curl.svg"),
("EZ-Bar_Curl","Curl con barra Z","biceps","baja",None,["curl barra z","curl con barra w"],None),
("Dumbbell_Bicep_Curl","Curl de bíceps con mancuernas","biceps","baja",None,["curl de biceps","curl biceps","curl de pie","curl con mancuernas"],"bicep-curls.svg"),
("Dumbbell_Alternate_Bicep_Curl","Curl alternado con mancuernas","biceps","baja",None,["curl alternado"],None),
("Hammer_Curls","Curl martillo","biceps","baja",None,["curl martillo con mancuernas","curl neutro"],"bicep-hammer-curl.svg"),
("Cross_Body_Hammer_Curl","Curl martillo cruzado","biceps","baja",None,[],None),
("Incline_Dumbbell_Curl","Curl inclinado con mancuernas","biceps","baja",None,["curl en banco inclinado"],None),
("Concentration_Curls","Curl concentrado","biceps","baja",None,[],"concentration-curls.svg"),
("Preacher_Curl","Curl predicador con barra","biceps","baja",None,["curl banco scott","curl predicador","curl scott"],"preacher-curl-3.svg"),
("One_Arm_Dumbbell_Preacher_Curl","Curl predicador a una mano","biceps","baja",None,["curl predicador a una mano"],"one-arm-preacher-curl.svg"),
("Machine_Preacher_Curls","Curl predicador en máquina","biceps","baja",None,["curl scott en maquina"],None),
("Machine_Bicep_Curl","Curl de bíceps en máquina","biceps","baja",None,["curl en maquina"],None),
("Standing_Biceps_Cable_Curl","Curl de bíceps en polea","biceps","baja",None,["curl en polea","curl polea baja"],None),
("High_Cable_Curls","Curl en polea alta","biceps","baja",None,["curl polea alta"],"high-cable-curls.svg"),
("Lying_Cable_Curl","Curl en polea acostado","biceps","baja",None,["curl en polea acostado"],"lying-bicep-cable-curl.svg"),
("Cable_Hammer_Curls_-_Rope_Attachment","Curl martillo en polea con soga","biceps","baja",None,["curl con soga","curl martillo en polea"],"hammer-curls-with-rope.svg"),
("Spider_Curl","Curl araña","biceps","baja",None,["curl arana","spider curl"],"spider-curl.svg"),
("Reverse_Barbell_Curl","Curl invertido con barra","biceps","baja",None,["curl inverso","curl pronado"],"biceps-curl-reverse.svg"),
("Zottman_Curl","Curl Zottman","biceps","baja",None,[],None),
# ---------- TRÍCEPS
("Triceps_Pushdown","Extensión de tríceps en polea con barra","triceps","baja",None,["extension de triceps","extension triceps polea","extension de triceps en polea","jalon de triceps","pushdown","triceps en polea"],"low-triceps-extension.svg"),
("Triceps_Pushdown_-_Rope_Attachment","Extensión de tríceps en polea con soga","triceps","baja",None,["extension triceps soga","triceps con soga"],None),
("Triceps_Pushdown_-_V-Bar_Attachment","Extensión de tríceps en polea con barra V","triceps","baja",None,[],None),
("Reverse_Grip_Triceps_Pushdown","Extensión de tríceps en polea agarre supino","triceps","baja",None,[],None),
("Cable_Rope_Overhead_Triceps_Extension","Extensión de tríceps sobre la cabeza en polea","triceps","baja",None,["triceps trasnuca en polea","extension por encima de la cabeza"],None),
("Cable_One_Arm_Tricep_Extension","Extensión de tríceps en polea a una mano","triceps","baja",None,["extension de triceps a una mano"],"one-arm-triceps-extension.svg"),
("EZ-Bar_Skullcrusher","Press francés con barra Z","triceps","baja",None,["press frances","rompecraneos","skullcrusher"],"lying-close-grip-triceps-press-to-chin.svg"),
("Lying_Dumbbell_Tricep_Extension","Press francés con mancuernas","triceps","baja",None,["extension de triceps acostado"],"lying-triceps-extension-across-face.svg"),
("Standing_Dumbbell_Triceps_Extension","Extensión de tríceps trasnuca con mancuerna","triceps","baja",None,["triceps trasnuca","copa","extension trasnuca"],None),
("Seated_Triceps_Press","Press de tríceps sentado","triceps","baja",None,["press de triceps sentado"],"seated-triceps-press.svg"),
("Tricep_Dumbbell_Kickback","Patada de tríceps","triceps","baja",None,["patada de triceps","kickback"],"triceps-kickback.svg"),
("Incline_Barbell_Triceps_Extension","Extensión de tríceps en banco inclinado","triceps","baja",None,["extension de triceps inclinado"],"incline-triceps-extensions.svg"),
("Machine_Triceps_Extension","Extensión de tríceps en máquina","triceps","baja",None,[],None),
("Dip_Machine","Fondos en máquina","triceps","baja",None,["fondo de maquina asistido","fondos asistidos","fondos en maquina","fondos asistidos en maquina","fondo asistido","maquina de fondos"],None),
("Parallel_Bar_Dip","Fondos en paralelas","triceps","baja","reps",["fondos en paralelas","fondos","dips"],"tricep-dips.svg"),
("Bench_Dips","Fondos en banco","triceps","baja","reps",["fondos banco","fondos entre bancos"],"bench-dips.svg"),
("Close-Grip_Dumbbell_Press","Press cerrado con mancuernas","triceps","baja",None,[],None),
("JM_Press","Press JM","triceps","baja",None,[],None),
("Push-Ups_-_Close_Triceps_Position","Flexiones cerradas (diamante)","triceps","baja","reps",["flexiones diamante"],None),
# ---------- SENTADILLA
("Barbell_Squat","Sentadilla con barra","sentadilla","alta",None,["sentadilla","sentadillas","sentadilla trasera","sentadilla libre","back squat"],"squats-2.svg"),
("Barbell_Full_Squat","Sentadilla profunda con barra","sentadilla","alta",None,[],None),
("Front_Barbell_Squat","Sentadilla frontal con barra","sentadilla","media",None,["sentadilla frontal","front squat"],None),
("Box_Squat","Sentadilla al cajón con barra","sentadilla","alta",None,["sentadilla al cajon"],None),
("Goblet_Squat","Sentadilla goblet","sentadilla","baja",None,["sentadilla copa","goblet"],None),
("Dumbbell_Squat","Sentadilla con mancuernas","sentadilla","media",None,[],None),
("Bodyweight_Squat","Sentadilla sin peso","sentadilla","baja","reps",["sentadilla libre sin peso","air squat"],"squats.svg"),
("Smith_Machine_Squat","Sentadilla en Smith","sentadilla","media",None,["sentadilla multipower"],None),
("Hack_Squat","Sentadilla hack en máquina","sentadilla","baja",None,["hack","sentadilla hack","hack squat"],None),
("Leg_Press","Prensa de piernas","sentadilla","baja",None,["prensa","prensa de pierna","prensa 45","prensa inclinada"],"leg-press-1.svg"),
("Narrow_Stance_Leg_Press","Prensa de piernas pies juntos","sentadilla","baja",None,[],None),
("Lying_Machine_Squat","Sentadilla péndulo en máquina","sentadilla","baja",None,["sentadilla pendulo","pendulo"],None),
("Plie_Dumbbell_Squat","Sentadilla sumo con mancuerna","sentadilla","baja",None,["sentadilla sumo","sentadilla plie"],None),
("Wide_Stance_Barbell_Squat","Sentadilla sumo con barra","sentadilla","alta",None,[],None),
# ---------- UNILATERAL
("Dumbbell_Lunges","Estocadas con mancuernas","unilateral","baja",None,["estocadas","zancadas","estocadas con mancuerna","lunges"],"lunges.svg"),
("Barbell_Lunge","Estocadas con barra","unilateral","media",None,[],None),
("Barbell_Walking_Lunge","Estocadas caminando con barra","unilateral","media",None,[],None),
("Bodyweight_Walking_Lunge","Estocadas caminando","unilateral","baja","reps",["zancadas caminando"],None),
("Dumbbell_Rear_Lunge","Estocadas hacia atrás con mancuernas","unilateral","baja",None,["estocada atras","zancada inversa"],None),
("Split_Squat_with_Dumbbells","Sentadilla búlgara con mancuernas","unilateral","baja",None,["sentadilla bulgara","bulgaras","split squat"],None),
("One_Leg_Barbell_Squat","Sentadilla búlgara con barra","unilateral","media",None,[],None),
("Smith_Single-Leg_Split_Squat","Sentadilla dividida en Smith","unilateral","baja",None,["bulgara en smith"],None),
("Dumbbell_Step_Ups","Subida al cajón con mancuernas","unilateral","baja",None,["step up","subida al banco"],None),
("Barbell_Step_Ups","Subida al cajón con barra","unilateral","media",None,[],None),
# ---------- CUÁDRICEPS / FEMORAL AISLADO
("Leg_Extensions","Extensión de cuádriceps","cuadriceps","baja",None,["sillon de cuadriceps","extensiones de cuadriceps","cuadriceps en maquina","extension de piernas","sillon cuadriceps"],None),
("Single-Leg_Leg_Extension","Extensión de cuádriceps a una pierna","cuadriceps","baja",None,[],None),
("Lying_Leg_Curls","Curl femoral acostado","femoral","baja",None,["curl femoral","camilla femoral","femorales","femoral acostado","isquios en maquina"],None),
("Seated_Leg_Curl","Curl femoral sentado","femoral","baja",None,["femoral sentado"],None),
("Standing_Leg_Curl","Curl femoral de pie","femoral","baja",None,["femoral de pie"],None),
("Ball_Leg_Curl","Curl femoral con pelota","femoral","baja","reps",[],None),
("Natural_Glute_Ham_Raise","Curl nórdico","femoral","baja","reps",["nordico","curl nordico"],None),
# ---------- BISAGRA DE CADERA
("Barbell_Deadlift","Peso muerto con barra","bisagra","alta",None,["peso muerto","deadlift","peso muerto convencional"],None),
("Romanian_Deadlift","Peso muerto rumano con barra","bisagra","alta",None,["peso muerto rumano","rdl","rumano"],None),
("Stiff-Legged_Dumbbell_Deadlift","Peso muerto rumano con mancuernas","bisagra","media",None,["peso muerto con mancuernas","rumano con mancuernas","peso muerto piernas rigidas con mancuernas"],None),
("Stiff-Legged_Barbell_Deadlift","Peso muerto piernas rígidas con barra","bisagra","alta",None,["peso muerto piernas rigidas"],None),
("Sumo_Deadlift","Peso muerto sumo","bisagra","alta",None,[],None),
("Trap_Bar_Deadlift","Peso muerto con barra hexagonal","bisagra","media",None,["peso muerto hexagonal","trap bar"],None),
("Rack_Pulls","Peso muerto desde soportes (rack pull)","bisagra","alta",None,["rack pull"],None),
("Good_Morning","Buenos días con barra","bisagra","alta",None,["buenos dias","good morning"],None),
("Kettlebell_One-Legged_Deadlift","Peso muerto a una pierna con kettlebell","bisagra","media",None,["peso muerto a una pierna"],None),
("Smith_Machine_Stiff-Legged_Deadlift","Peso muerto rumano en Smith","bisagra","alta",None,[],None),
("Pull_Through","Pull through en polea","bisagra","baja",None,["tiron entre piernas en polea"],None),
("Hyperextensions_Back_Extensions","Hiperextensiones (extensión lumbar)","bisagra","media","reps",["hiperextensiones","extension lumbar","banco romano","lumbares"],"hyperextensions.svg"),
("Reverse_Hyperextension","Hiperextensión inversa","bisagra","media",None,[],None),
("Weighted_Ball_Hyperextension","Extensión lumbar en pelota","bisagra","baja","reps",["extension lumbar en pelota"],"back-extension-on-stability-ball.svg"),
(None,"Superman (extensión lumbar en el piso)","bisagra","baja","reps",["supermans","superman"],"supermans.svg"),
# ---------- GLÚTEO / ADUCTORES / ABDUCTORES
("Barbell_Hip_Thrust","Hip thrust con barra","gluteo","baja",None,["hip thrust","empuje de cadera"],None),
("Barbell_Glute_Bridge","Puente de glúteo con barra","gluteo","baja",None,["puente de gluteo con barra"],None),
("Butt_Lift_Bridge","Puente de glúteo","gluteo","baja","reps",["puente de gluteo","puente"],"bridge.svg"),
("Single_Leg_Glute_Bridge","Puente de glúteo a una pierna","gluteo","baja","reps",[],None),
("One-Legged_Cable_Kickback","Patada de glúteo en polea","gluteo","baja",None,["patada de gluteo","patada en polea"],None),
("Glute_Kickback","Patada de glúteo en el piso","gluteo","baja","reps",[],None),
("Thigh_Abductor","Abductores en máquina","abductores","baja",None,["abductores","abduccion de cadera","maquina de abductores"],None),
("Thigh_Adductor","Aductores en máquina","aductores","baja",None,["aductores","aduccion de cadera","maquina de aductores"],None),
("Cable_Hip_Adduction","Aducción de cadera en polea","aductores","baja",None,[],None),
("Monster_Walk","Caminata con banda (monster walk)","abductores","baja","reps",["monster walk"],None),
# ---------- GEMELOS
("Standing_Calf_Raises","Gemelos de pie en máquina","gemelos","baja",None,["gemelos","pantorrillas","elevacion de talones","gemelos de pie"],None),
("Seated_Calf_Raise","Gemelos sentado en máquina","gemelos","baja",None,["gemelos sentado"],None),
("Calf_Press_On_The_Leg_Press_Machine","Gemelos en prensa","gemelos","baja",None,["gemelos en prensa"],None),
("Standing_Dumbbell_Calf_Raise","Gemelos de pie con mancuerna","gemelos","baja",None,[],None),
("Smith_Machine_Calf_Raise","Gemelos en Smith","gemelos","baja",None,[],None),
("Donkey_Calf_Raises","Gemelos burro","gemelos","baja",None,[],None),
("Dumbbell_Seated_One-Leg_Calf_Raise","Gemelo sentado a una pierna","gemelos","baja",None,[],None),
# ---------- CORE
("Plank","Plancha","core_anti","baja","seg",["plancha frontal","plancha abdominal"],None),
("Side_Bridge","Plancha lateral","core_anti","baja","seg",[],"side-plank.svg"),
("Dead_Bug","Dead bug","core_anti","baja","reps",["bicho muerto"],None),
("Ab_Roller","Rueda abdominal","core_anti","media","reps",["ab wheel","rueda"],None),
("Mountain_Climbers","Escaladores","core_anti","baja","reps",["mountain climbers"],None),
("Crunches","Crunch abdominal","core_flex","baja","reps",["crunch","abdominales","abdominales cortos"],"crunches.svg"),
("Cable_Crunch","Crunch en polea","core_flex","baja",None,["abdominal en polea","crunch arrodillado en polea"],None),
("Ab_Crunch_Machine","Crunch en máquina","core_flex","baja",None,["abdominales en maquina"],None),
("Decline_Crunch","Crunch declinado","core_flex","baja","reps",[],"decline-crunch.svg"),
("Cross-Body_Crunch","Crunch cruzado","core_flex","baja","reps",[],"cross-body-crunch.svg"),
("Reverse_Crunch","Crunch inverso","core_flex","baja","reps",[],None),
("Sit-Up","Abdominales completos (sit-up)","core_flex","media","reps",["sit up"],None),
("Hanging_Leg_Raise","Elevación de piernas colgado","core_flex","baja","reps",["elevaciones de piernas colgado","piernas colgado"],None),
("Knee_Hip_Raise_On_Parallel_Bars","Elevación de rodillas en paralelas (silla romana)","core_flex","baja","reps",["silla romana","elevacion de rodillas","capitan"],None),
("Flat_Bench_Lying_Leg_Raise","Elevación de piernas acostado","core_flex","media","reps",["elevacion de piernas","elevaciones de piernas"],"leg-raises.svg"),
("Bent-Knee_Hip_Raise","Elevación de cadera con rodillas flexionadas","core_flex","baja","reps",["elevacion de cadera"],"bent-knee-hip-raise.svg"),
("Oblique_Crunches_-_On_The_Floor","Crunch oblicuo","core_rot","baja","reps",["oblicuos"],None),
("Russian_Twist","Giro ruso","core_rot","media","reps",["russian twist"],None),
("Pallof_Press","Press Pallof","core_rot","baja",None,["pallof","antirrotacion"],None),
("Standing_Cable_Wood_Chop","Leñador en polea","core_rot","baja",None,["lenador","woodchop","lenador en polea"],None),
("Dumbbell_Side_Bend","Inclinación lateral con mancuerna","core_rot","baja",None,["flexion lateral con mancuerna"],None),
# ---------- CARGAS / AGARRE / ANTEBRAZO
("Farmers_Walk","Caminata del granjero","carga","media","kg+m",["farmer walk","paseo del granjero","caminata granjero"],None),
(None,"Caminata de maleta (una mano)","carga","baja","kg+m",["suitcase carry","caminata con una mancuerna"],None),
(None,"Dead hang (colgado de la barra)","carga","baja","seg",["dead hang","colgarse de la barra","colgado en barra"],None),
("Plate_Pinch","Pinza de discos","carga","baja","kg+seg",["pinza de discos","plate pinch"],None),
("Wrist_Roller","Rodillo de muñeca","antebrazo","baja","reps",[],None),
("Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench","Curl de muñeca con mancuerna","antebrazo","baja",None,["curl de muneca"],None),
("Palms-Down_Wrist_Curl_Over_A_Bench","Curl de muñeca invertido con barra","antebrazo","baja",None,[],None),
("Sled_Push","Empuje de trineo","carga","baja","kg+m",["trineo","empuje de trineo"],None),
# ---------- POTENCIA
("Power_Clean","Cargada de potencia","potencia","alta",None,["power clean","cargada"],None),
("Hang_Clean","Cargada colgante","potencia","alta",None,["hang clean"],None),
("Clean_and_Press","Cargada y press","potencia","alta",None,[],None),
("Push_Press","Push press","potencia","media",None,[],None),
("Dumbbell_Clean","Cargada con mancuernas","potencia","media",None,[],None),
("One-Arm_Kettlebell_Swings","Swing con kettlebell","potencia","media",None,["swing","kettlebell swing"],None),
("Kettlebell_Thruster","Thruster con kettlebell","potencia","media",None,["thruster"],None),
("Overhead_Slam","Slam con balón medicinal","potencia","baja","reps",["slam ball","slam"],None),
("Medicine_Ball_Chest_Pass","Pase de pecho con balón medicinal","potencia","baja","reps",[],None),
("Battling_Ropes","Cuerdas de batalla","potencia","baja","seg",["battle ropes","sogas de batalla"],None),
# ---------- PLIOMETRÍA
("Front_Box_Jump","Salto al cajón","pliometria","baja","reps",["box jump","salto al cajon"],None),
("Freehand_Jump_Squat","Sentadilla con salto","pliometria","baja","reps",["jump squat"],None),
("Standing_Long_Jump","Salto largo","pliometria","baja","reps",[],None),
("Split_Jump","Salto en estocada","pliometria","baja","reps",[],None),
("Knee_Tuck_Jump","Salto con rodillas al pecho","pliometria","baja","reps",[],None),
("Plyo_Push-up","Flexiones pliométricas","pliometria","baja","reps",["flexiones con palmada"],None),
("Lateral_Bound","Saltos laterales","pliometria","baja","reps",[],None),
# ---------- CARDIO
("Walking_Treadmill","Cinta (caminata)","cardio","baja","cardio",["cinta","caminata en cinta","cinta caminando"],None),
("Running_Treadmill","Cinta (trote o carrera)","cardio","baja","cardio",["correr en cinta","trote"],None),
("Elliptical_Trainer","Elíptica","cardio","baja","cardio",["eliptica"],None),
("Bicycling_Stationary","Bicicleta fija","cardio","baja","cardio",["bici","bicicleta","spinning"],None),
("Recumbent_Bike","Bicicleta reclinada","cardio","baja","cardio",["bici reclinada"],None),
("Rowing_Stationary","Remo ergómetro","cardio","baja","cardio",["remoergometro","remo indoor"],None),
("Stairmaster","Escaladora","cardio","baja","cardio",["stairmaster","escalera"],None),
("Rope_Jumping","Soga","cardio","baja","cardio",["saltar la soga","cuerda"],None),
]
